apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: uni-resolver-dev
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 5m
        memory: 128Mi
      type: Container